// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbRM8h95NUKe8hvPB1ND0Aic0PZrMkcM',
    appId: '1:442619974988:android:188abce9d764a9ffaa6be9',
    messagingSenderId: '442619974988',
    projectId: 'events4me-563e3',
    storageBucket: 'events4me-563e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxFMNHwhzn3dntlyYAW_6bnPgWO6yHj8',
    appId: '1:442619974988:ios:c472007ce053a510aa6be9',
    messagingSenderId: '442619974988',
    projectId: 'events4me-563e3',
    storageBucket: 'events4me-563e3.appspot.com',
    androidClientId: '442619974988-fog7kq5ckeq1f2cik26j1m8vekt28slr.apps.googleusercontent.com',
    iosClientId: '442619974988-57a4u7fstel0en511qe3hso3dldatis7.apps.googleusercontent.com',
    iosBundleId: 'com.events4me.events4me',
  );
}
